[package]
name = "shooter"
version = "0.1.0"
authors = ["Andrew"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
nalgebra = "0.23.2"
rand = "0.8.0"

[dev-dependencies]
quickcheck = "*"
