[package]
name = "shooter"
version = "0.1.0"
authors = ["Andrew"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", rev = "3183367f397aa46fade5912fe23b53ca68b55bb4" }
nalgebra = "0.23.2"
rand = "0.8.0"

[dev-dependencies]
quickcheck = "0.9.2"
