[package]
name = "shooter"
version = "0.1.0"
authors = ["Andrew"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", rev = "bd1e015899d5f6b086e7603dffe48f3dd8806e49" }
nalgebra = "0.23.2"
rand = "0.8.0"

[dev-dependencies]
quickcheck = "0.9.2"
